[
  {
    "_id": "6714b22fcb6fbc8f42231f6d",
    "title": "Luxurious 2BHK Apartment",
    "location": "Vrindavan",
    "price": "₹45,00,000",
    "beds": "2 Beds",
    "area": "1200 sqft",
    "parking": "1 Parking",
    "type": "Buy",
    "propertyType": "Apartment",
    "description": "A modern 2BHK apartment with spacious living areas and beautiful interiors.",
    "images": ["/img/a1.jpg", "/img/a2.jpg", "/img/a3.jpg"]
  },
  {
    "_id": "6714b22fcb6fbc8f42231f6e",
    "title": "Spacious Villa with Garden",
    "location": "Mathura",
    "price": "₹1,20,00,000",
    "beds": "4 Beds",
    "area": "3500 sqft",
    "parking": "2 Parking",
    "type": "Buy",
    "propertyType": "Villa",
    "description": "A luxurious villa with a private garden and modern amenities for ultimate comfort.",
    "images": ["/img/a1.jpg", "/img/a2.jpg", "/img/a3.jpg"]
  },
  {
    "_id": "6714b22fcb6fbc8f42231f6f",
    "title": "Commercial Shop Space",
    "location": "Delhi",
    "price": "₹90,00,000",
    "beds": "-",
    "area": "1500 sqft",
    "parking": "2 Parking",
    "type": "Rent",
    "propertyType": "Commercial",
    "description": "Premium commercial space in the heart of the city, ideal for shops or offices.",
    "images": ["/img/a1.jpg", "/img/a2.jpg", "/img/a3.jpg"]
  },
  {
    "_id": "6714b22fcb6fbc8f42231f70",
    "title": "Open Land Plot",
    "location": "Agra",
    "price": "₹30,00,000",
    "beds": "-",
    "area": "2000 sqft",
    "parking": "-",
    "type": "Sell",
    "propertyType": "Land",
    "description": "A prime land plot perfect for building your dream home or investment purposes.",
    "images": ["/img/a1.jpg", "/img/a3.jpg", "/img/a3.jpg"]
  },
  {
    "_id": "6714b22fcb6fbc8f42231f71",
    "title": "Modern 3BHK Apartment",
    "location": "Aligarh",
    "price": "₹60,00,000",
    "beds": "3 Beds",
    "area": "1500 sqft",
    "parking": "1 Parking",
    "type": "Buy",
    "propertyType": "Apartment",
    "description": "A modern apartment with sleek design and all contemporary facilities.",
    "images": ["/img/a1.jpg", "/img/a1.jpg", "/img/a3.jpg"]
  },
  {
    "_id": "6714b22fcb6fbc8f42231f72",
    "title": "Elegant Villa with Pool",
    "location": "Vrindavan",
    "price": "₹1,50,00,000",
    "beds": "5 Beds",
    "area": "4000 sqft",
    "parking": "2 Parking",
    "type": "Buy",
    "propertyType": "Villa",
    "description": "An elegant villa featuring a private pool, spacious interiors, and luxury amenities.",
    "images": ["/img/a1.jpg", "/img/a2.jpg", "/img/a3.jpg"]
  },
  {
    "_id": "6714b22fcb6fbc8f42231f73",
    "title": "Retail Space for Rent",
    "location": "Mumbai",
    "price": "₹2,50,000/month",
    "beds": "-",
    "area": "1200 sqft",
    "parking": "1 Parking",
    "type": "Rent",
    "propertyType": "Commercial",
    "description": "Retail space available in a high-traffic area, perfect for shops and businesses.",
    "images": ["/img/a1.jpg", "/img/a2.jpg", "/img/a3.jpg"]
  },
  {
    "_id": "6714b22fcb6fbc8f42231f74",
    "title": "Greenfield Land Plot",
    "location": "Noida",
    "price": "₹50,00,000",
    "beds": "-",
    "area": "2500 sqft",
    "parking": "-",
    "type": "Sell",
    "propertyType": "Land",
    "description": "A greenfield land plot suitable for residential construction or commercial use.",
    "images": ["/img/a1.jpg", "/img/a2.jpg", "/img/a3.jpg"]
  },
  {
    "_id": "6714b22fcb6fbc8f42231f75",
    "title": "2BHK Apartment with Balcony",
    "location": "Mathura",
    "price": "₹40,00,000",
    "beds": "2 Beds",
    "area": "1100 sqft",
    "parking": "1 Parking",
    "type": "Buy",
    "propertyType": "Apartment",
    "description": "A cozy 2BHK apartment with balcony and well-ventilated rooms.",
    "images": ["/img/a1.jpg", "/img/a2.jpg", "/img/a3.jpg"]
  },
  {
    "_id": "6714b22fcb6fbc8f42231f76",
    "title": "Luxury Villa with Garden",
    "location": "Agra",
    "price": "₹1,80,00,000",
    "beds": "4 Beds",
    "area": "3800 sqft",
    "parking": "2 Parking",
    "type": "Buy",
    "propertyType": "Villa",
    "description": "A luxurious villa with a landscaped garden, modern interiors, and premium amenities.",
    "images": ["/img/a1.jpg", "/img/a2.jpg", "/img/a3.jpg"]
  }
]
